"""Legal lifecycle transitions over the Phase 2 journal."""

from __future__ import annotations

from stateback.transitions.commands import (
    ApprovalGrant,
    ApprovalReject,
    CancelAwaitingApproval,
    CancelPendingPolicy,
    CancelReady,
    ClaimCompensationExecution,
    ClaimCompensationRetryAttempt,
    ClaimExecution,
    CompensationApplied,
    CompensationEscalate,
    CompensationFailedEscalate,
    CompensationFailedRetry,
    CompensationOutcomeFailed,
    CompensationOutcomeUnknown,
    CompensationUnknownApplied,
    CompensationUnknownEscalate,
    CompensationUnknownFailed,
    CompensationUnknownRetry,
    CreateOperation,
    ExecutionApplied,
    ExecutionNotAppliedFail,
    ExecutionNotAppliedRetry,
    ExecutionRequireVerification,
    ExecutionUnknown,
    FailedStartCompensation,
    ManualSafeRetry,
    ManualStartCompensation,
    ManualStartVerification,
    PolicyAllow,
    PolicyDeny,
    PolicyRequireApproval,
    RetryCompensationAfterVerification,
    StartCompensationVerification,
    SucceededStartCompensation,
    TransitionCommand,
    UnknownEscalate,
    UnknownReconcileApplied,
    UnknownReconcileNotApplied,
    UnknownSafeRetry,
    UnknownStartVerification,
    VerificationApplied,
    VerificationEscalate,
    VerificationInconclusive,
    VerificationNotAppliedFail,
    VerificationNotAppliedRetry,
)
from stateback.transitions.kinds import (
    KIND_TO_EDGE,
    CompensationProgressKind,
    TransitionKind,
)
from stateback.transitions.outbox import (
    OUTBOX_COMMAND_FOR_KIND,
    OUTBOX_COMMAND_FOR_PROGRESS_KIND,
)
from stateback.transitions.results import TransitionOutcome, TransitionResult
from stateback.transitions.service import TransitionService

__all__ = [
    "ApprovalGrant",
    "ApprovalReject",
    "CancelAwaitingApproval",
    "CancelPendingPolicy",
    "CancelReady",
    "ClaimCompensationExecution",
    "ClaimCompensationRetryAttempt",
    "ClaimExecution",
    "CompensationApplied",
    "CompensationFailedEscalate",
    "CompensationFailedRetry",
    "CompensationEscalate",
    "CompensationOutcomeFailed",
    "CompensationOutcomeUnknown",
    "CompensationProgressKind",
    "CompensationUnknownApplied",
    "CompensationUnknownEscalate",
    "CompensationUnknownFailed",
    "CompensationUnknownRetry",
    "CreateOperation",
    "ExecutionApplied",
    "ExecutionNotAppliedFail",
    "ExecutionNotAppliedRetry",
    "ExecutionRequireVerification",
    "ExecutionUnknown",
    "FailedStartCompensation",
    "KIND_TO_EDGE",
    "ManualSafeRetry",
    "ManualStartCompensation",
    "ManualStartVerification",
    "OUTBOX_COMMAND_FOR_KIND",
    "OUTBOX_COMMAND_FOR_PROGRESS_KIND",
    "PolicyAllow",
    "PolicyDeny",
    "PolicyRequireApproval",
    "RetryCompensationAfterVerification",
    "StartCompensationVerification",
    "SucceededStartCompensation",
    "TransitionCommand",
    "TransitionKind",
    "TransitionOutcome",
    "TransitionResult",
    "TransitionService",
    "UnknownEscalate",
    "UnknownReconcileApplied",
    "UnknownReconcileNotApplied",
    "UnknownSafeRetry",
    "UnknownStartVerification",
    "VerificationApplied",
    "VerificationEscalate",
    "VerificationInconclusive",
    "VerificationNotAppliedFail",
    "VerificationNotAppliedRetry",
]
