"""Deterministic script enums for the reference adapter queues."""

from __future__ import annotations

from enum import StrEnum


class ReferenceExecuteScript(StrEnum):
    APPLIED = "APPLIED"
    NOT_APPLIED_VALIDATION = "NOT_APPLIED_VALIDATION"
    NOT_APPLIED_REJECTED = "NOT_APPLIED_REJECTED"
    NOT_APPLIED_UNAVAILABLE = "NOT_APPLIED_UNAVAILABLE"
    NOT_APPLIED_RATE_LIMIT = "NOT_APPLIED_RATE_LIMIT"
    NOT_APPLIED_AUTH = "NOT_APPLIED_AUTH"
    UNKNOWN_TIMEOUT_AFTER_SEND = "UNKNOWN_TIMEOUT_AFTER_SEND"
    UNKNOWN_MALFORMED = "UNKNOWN_MALFORMED"
    UNKNOWN_RATE_LIMIT_AMBIGUOUS = "UNKNOWN_RATE_LIMIT_AMBIGUOUS"
    APPLIED_RESPONSE_LOST = "APPLIED_RESPONSE_LOST"


class ReferenceVerifyScript(StrEnum):
    STORE = "STORE"
    APPLIED = "APPLIED"
    NOT_APPLIED = "NOT_APPLIED"
    UNKNOWN_TRANSPORT = "UNKNOWN_TRANSPORT"
    UNKNOWN_INCONCLUSIVE = "UNKNOWN_INCONCLUSIVE"
    UNKNOWN_MALFORMED = "UNKNOWN_MALFORMED"
    UNKNOWN_INCONSISTENT = "UNKNOWN_INCONSISTENT"


class ReferenceCompensateScript(StrEnum):
    APPLIED = "APPLIED"
    NOT_APPLIED_REJECTED = "NOT_APPLIED_REJECTED"
    UNKNOWN_TIMEOUT_AFTER_SEND = "UNKNOWN_TIMEOUT_AFTER_SEND"
    UNKNOWN_MALFORMED = "UNKNOWN_MALFORMED"
